server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /controle-estoque-api
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Tonyhawkcrackeado1
    url: jdbc:mysql://localhost:3306/controle_de_estoque?createDatabaseIfNotExist=true
    username: root
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  org:
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
